SetExtension("scorecardPaperSize", "letter", "CompetitionConfig", "groupifier")
SetExtension("scorecardOrder", "stacked", "CompetitionConfig", "groupifier")
SetExtension("printStations", false, "CompetitionConfig", "groupifier") 
SetExtension("printScrambleCheckerForTopRankedCompetitors", true, "CompetitionConfig", "groupifier")
SetExtension("printScrambleCheckerForFinalRounds", true, "CompetitionConfig", "groupifier")
